apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mern-stack
  name: mern-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mern-stack
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mern-stack
    spec:
      containers:
      - image: 596027898727.dkr.ecr.us-east-1.amazonaws.com/mern-stack:0c5d849ba3fae1ae975de5b65f6053ca2e88f009
        name: mern-stack
        imagePullPolicy: Always
        resources: {}
        ports:
          - containerPort: 80
      imagePullSecrets:
      - name: ecr
status: {}